const config = require('@clarabridge/unified-ui/src/configuration');

const spacingTheme = config.SPACING.reduce((accumulator, spacing) => (accumulator[spacing] = spacing + 'px', accumulator), {});

const widthsAndHeightsTheme = {
    ...config.WIDTHS_AND_HEIGHTS.PIXEL.reduce((accumulator, dimension) =>
        (accumulator[dimension] = dimension + 'px', accumulator), {}),
    ...config.WIDTHS_AND_HEIGHTS.PERCENT.reduce((accumulator, dimension) =>
        (accumulator[dimension+'-percent'] = dimension + '%', accumulator), {}),
    ...config.WIDTHS_AND_HEIGHTS.VIEWPORT.reduce((accumulator, dimension) =>
        (accumulator[dimension+'-vh'] = dimension + 'vh', accumulator), {}),
};

module.exports = {
    corePlugins: [
        'backgroundColor',
        'opacity',
        'padding',
        'margin',
        'position',
        'flex',
        'flexDirection',
        'flexGrow',
        'flexShrink',
        'flexWrap',
        'alignItems',
        'alignContent',
        'justifyContent',
        'justifyItems',
        'justifySelf',
        'alignSelf',
        'display',
        'width',
        'minWidth',
        'maxWidth',
        'height',
        'minHeight',
        'maxHeight',
        'borderStyle',
        'borderWidth',
        'borderColor',
        'borderRadius',
        'cursor',
        'pointerEvents',
        'outline',
        'float',
        'clear',
        'textAlign',
        'textTransform',
        'verticalAlign',
        'wordBreak',
        'whitespace',
        'textOverflow',
        'textDecoration',
        'textColor',
        'fontFamily',
        'fontSize',
        'lineHeight',
        'transitionProperty',
        'boxSizing',
        'boxShadow',
        'overflow',
    ],
    purge: [],
    important: true,
    darkMode: false,
    theme: {
        screens: false,
        colors: config.COLORS,
        padding: spacingTheme,
        margin: spacingTheme,
        width: widthsAndHeightsTheme,
        minWidth: widthsAndHeightsTheme,
        maxWidth: widthsAndHeightsTheme,
        height: widthsAndHeightsTheme,
        minHeight: widthsAndHeightsTheme,
        maxHeight: widthsAndHeightsTheme,
        borderWidth: config.BORDERS.reduce((accumulator, border) => (accumulator[border] = border + 'px', accumulator), {}),
        borderRadius: config.BORDERS.reduce((accumulator, border) => (accumulator[border] = border + 'px', accumulator), {}),
        fontFamily: config.FONT.FAMILIES,
        fontSize: config.FONT.SIZES,
        lineHeight: { ...config.FONT.SIZES, '0': 0 },
    },
    variants: {
        textColor: ['hover'],
        backgroundColor: ['hover'],
        borderColor: ['hover'],
        opacity: ['hover'],
        padding: [],
        margin: [],
        width: [],
        minWidth: [],
        maxWidth: [],
        height: [],
        minHeight: [],
        maxHeight: [],
        outline:[],
        textDecoration:[],
        boxShadow: [],
    },
    plugins: [],
}
